name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: |
          docker login --username baylorhenshaw --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest